bangpound_instagram_homepage:
    path:     /
    defaults: { _controller: BangpoundInstagramBundle:Default:index }

bangpound_instagram_location:
    path:     /location/{lat}/{lng}
    defaults: { _controller: BangpoundInstagramBundle:Default:location }
