parameters:
    bangpound_instagram.guzzle.client.class: GuzzleHttp\Client
    bangpound_instagram.client.class: Bangpound\Bundle\InstagramBundle\Client
    bangpound_instagram.instagram.class: Instagram\Instagram

services:
    bangpound_instagram.guzzle.client:
        class: %bangpound_instagram.guzzle.client.class%

    bangpound_instagram.client:
        class: %bangpound_instagram.client.class%
        arguments:
            - @bangpound_instagram.guzzle.client

    bangpound_instagram.instagram:
        class: %bangpound_instagram.instagram.class%
        arguments:
            - ~
            - @bangpound_instagram.client
        scope: request
